export const UPDATE_TIMECODE = "UPDATE_TIMECODE";
export const SET_POEME = "SET_POEME";
export const UPDATE_USER_TIME_REQUEST = "UPDATE_USER_TIME_REQUEST";
export const UPDATE_CURRENT_LINE = "UPDATE_CURRENT_LINE";
export const UPDATE_NEXT_LINE = "UPDATE_NEXT_LINE";
export const UPDATE_PREVIOUS_LINE = "UPDATE_PREVIOUS_LINE";
export const UPDATE_PLAYBACK = "UPDATE_PLAYBACK";
export const UPDATE_SOUND = "UPDATE_SOUND";
export const UPDATE_CURRENT_LOOP_VERS_COUNT = "UPDATE_CURRENT_LOOP_VERS_COUNT";
export const UPDATE_CURRENT_LOOP_CHAPTER_COUNT =
  "UPDATE_CURRENT_LOOP_CHAPTER_COUNT";
export const UPDATE_PLAYBACK_RATE = "UPDATE_PLAYBACK_RATE";
export const SET_INDEX = "SET_INDEX";
export const UPDATE_CURRENT_CHAPTER = "UPDATE_CURRENT_CHAPTER";
